name: Deploy Laravel to FTP

on:
  push:
    branches:
      - main # jalan setiap push ke branch main

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          exclude: |
            **/.git*
            **/.github*
            **/node_modules/**
            **/vendor/**
            **/.env
